package com.xgs.androidbase.bean.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xgs.androidbase.bean.ProjectTreeBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PROJECT_TREE_BEAN".
*/
public class ProjectTreeBeanDao extends AbstractDao<ProjectTreeBean, Long> {

    public static final String TABLENAME = "PROJECT_TREE_BEAN";

    /**
     * Properties of entity ProjectTreeBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Lid = new Property(0, Long.class, "lid", true, "_id");
        public final static Property CourseId = new Property(1, int.class, "courseId", false, "COURSE_ID");
        public final static Property Id = new Property(2, Long.class, "id", false, "ID");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Order = new Property(4, int.class, "order", false, "ORDER");
        public final static Property ParentChapterId = new Property(5, int.class, "parentChapterId", false, "PARENT_CHAPTER_ID");
        public final static Property Visible = new Property(6, int.class, "visible", false, "VISIBLE");
        public final static Property IsFollow = new Property(7, boolean.class, "isFollow", false, "IS_FOLLOW");
        public final static Property IsFixed = new Property(8, boolean.class, "isFixed", false, "IS_FIXED");
    }


    public ProjectTreeBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ProjectTreeBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PROJECT_TREE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: lid
                "\"COURSE_ID\" INTEGER NOT NULL ," + // 1: courseId
                "\"ID\" INTEGER," + // 2: id
                "\"NAME\" TEXT," + // 3: name
                "\"ORDER\" INTEGER NOT NULL ," + // 4: order
                "\"PARENT_CHAPTER_ID\" INTEGER NOT NULL ," + // 5: parentChapterId
                "\"VISIBLE\" INTEGER NOT NULL ," + // 6: visible
                "\"IS_FOLLOW\" INTEGER NOT NULL ," + // 7: isFollow
                "\"IS_FIXED\" INTEGER NOT NULL );"); // 8: isFixed
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PROJECT_TREE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ProjectTreeBean entity) {
        stmt.clearBindings();
 
        Long lid = entity.getLid();
        if (lid != null) {
            stmt.bindLong(1, lid);
        }
        stmt.bindLong(2, entity.getCourseId());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(3, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getOrder());
        stmt.bindLong(6, entity.getParentChapterId());
        stmt.bindLong(7, entity.getVisible());
        stmt.bindLong(8, entity.getIsFollow() ? 1L: 0L);
        stmt.bindLong(9, entity.getIsFixed() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ProjectTreeBean entity) {
        stmt.clearBindings();
 
        Long lid = entity.getLid();
        if (lid != null) {
            stmt.bindLong(1, lid);
        }
        stmt.bindLong(2, entity.getCourseId());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(3, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getOrder());
        stmt.bindLong(6, entity.getParentChapterId());
        stmt.bindLong(7, entity.getVisible());
        stmt.bindLong(8, entity.getIsFollow() ? 1L: 0L);
        stmt.bindLong(9, entity.getIsFixed() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ProjectTreeBean readEntity(Cursor cursor, int offset) {
        ProjectTreeBean entity = new ProjectTreeBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // lid
            cursor.getInt(offset + 1), // courseId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.getInt(offset + 4), // order
            cursor.getInt(offset + 5), // parentChapterId
            cursor.getInt(offset + 6), // visible
            cursor.getShort(offset + 7) != 0, // isFollow
            cursor.getShort(offset + 8) != 0 // isFixed
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ProjectTreeBean entity, int offset) {
        entity.setLid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCourseId(cursor.getInt(offset + 1));
        entity.setId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOrder(cursor.getInt(offset + 4));
        entity.setParentChapterId(cursor.getInt(offset + 5));
        entity.setVisible(cursor.getInt(offset + 6));
        entity.setIsFollow(cursor.getShort(offset + 7) != 0);
        entity.setIsFixed(cursor.getShort(offset + 8) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ProjectTreeBean entity, long rowId) {
        entity.setLid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ProjectTreeBean entity) {
        if(entity != null) {
            return entity.getLid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ProjectTreeBean entity) {
        return entity.getLid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
